version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      official-actions:
        patterns: ["actions/*"]
      docker-actions:
        patterns: ["docker/*"]
